version: '3'

services:
  api:
    build: ./api
    container_name: docker-burgerreact-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3024:3024" 
    environment:
      - PORT=3024
    networks:
      - docker-burgerreact-network

networks:
  docker-burgerreact-network:
    driver: bridge

